# Use a node image as a base
FROM node:21-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the Next.js app in dev mode
CMD ["npm", "run", "dev"]
